version: '3'

services:
  website:
    build: .
    restart: unless-stopped
    container_name: website
    expose:
      - 80
    networks: 
      - default
    environment:
      - VIRTUAL_HOST=nginx.carmesiservices.com
      - LETSENCRYPT_HOST=nginx.carmesiservices.com

networks:
  default:
    external:
      name: net-proxy

    
    
