version: '3'

services:
  api:
    build:
      context: .
    image: api-mysql:v1.0
    container_name: node-api-compose
    restart: always  # recomended: unless-stopped
    volumes:
      - .:/usr/src/app # solo para desarrollo
      - /usr/src/app/node_modules
    ports:
      - ${PORT}:${PORT}
    command: npm start
    depends_on:
      - db
  db:
    image: mysql:8.0.17
    container_name: mysql_db
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_ROOT_USER: ${DB_USER}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - '${DB_PORT}:3306'

  adminer:
    image: adminer
    container_name: adminer
    depends_on:
      - db
    ports:
      - '8082:8080'
      
volumes:
  db_data: